/*

NOTAS PREVIAS

1) lOS SIGUIENTES EJERCICIOS DEBERÁN REALIZARSE CON HTML, CSS Y JS Y LIBRERÍA JQUERY.
2) SE PROHÍBE EL USO DE PLUGINS DE TERCEROS DE LA LIBRERÍA JQUERYUI
3) LA LIBRERÍA JQUERY DEBE DESCARGARSE E IMPORTARSE LOCALMENTE Y NO SER IMPORTADA DESDE UN CDN

**** EJERCICIO 1****

SE PIDE IMPLEMENTAR EL CÓDIGO NECESARIO PARA PINTAR UN SEMÁFORO CON 3 LUCES, VERDE, ÁMBAR Y ROJO.
DONDE CADA LUZ PUEDE ESTAR ENCENDIDA Y MUESTRE SU COLOR O APAGARSE Y MOSTRARSE NEGRA.

EL FLUJO DE ENCENCIDO Y APAGADO DE LAS LUCES DEL SEMÁFORO DEBE SER EL SIGUIENTE

ESTADO 1: VERDE
ESTADO 2: ÁMBAR
ESTADO 3: ROJO
ESTADO 4: VERDE

EL SEMÁFORO CAMBIARÁ DE ESTADO SIGUIENDO EL ORDEN ANTERIOR, CADA VEZ QUE SE HAGA CLICK SOBRE 
UN BOTÓN INICIAL.

**** EJERCICIO 2****

IMPLEMENTAR EL CÓDIGO PARA PINTAR 3 BOTONES DE MANERA QUE AL PINCHAR SOBRE
CADA UNO DE ELLOS ESTOS MUESTREN Y OCULTEN 3 IMÁGENES DISTINAS, DE MANERA
QUE SOLO SE VEA UNA DE ELLAS, DEPENDIENDO DEL BOTÓN PINCHADO.

PINCHANDO EN EL BOTÓN 1- SE MUESTRA IMG-1 Y SE OCULTAN IMG-2 E IMG-3
PINCHANDO EN EL BOTÓN 2- SE MUESTRA IMG-2 Y SE OCULTAN IMG-1 E IMG-3
PINCHANDO EN EL BOTÓN 3- SE MUESTRA IMG-3 Y SE OCULTAN IMG-1 E IMG-2

DIFICULTAD EXTRA: 
REALIZAR EL MISMO EJERCICIO PARA CUALQUIER NÚMERO DE PESTAÑAS, ES DECIR, UNA CANTIDAD VARIABLE
DE LAS MISMAS, NO SIENDO SIEMPRE 3, SINO LAS QUE SE HAYAN CREADO EN EL HTML, DE MANERA QUE
DEPENDA DE ESE NÚMERO.



 */
